apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: r1uv4805l-nodejs 
  janus-idp.io/tekton: r1uv4805l-nodejs
  backstage.io/kubernetes-id: r1uv4805l-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: r1uv4805l-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml